version: '3.8'

services:
  api:
    build: .
    container_name: pawpatrol_api
    image: pawpatrol-back:atlas
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: "${SPRING_DATA_MONGODB_URI}"
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms256m -Xmx512m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3