spring.application.name=PAWPATROL_BACK

## Base H2 en memoria (temporal)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

### Conexion base de datos MongoDB (No relacional)
spring.data.mongodb.uri=${DATABASE_URL:mongodb+srv://JuanCaballero:Isabella2004@clustersirha.pc6me39.mongodb.net/?retryWrites=true&w=majority&appName=ClusterSirha}
spring.data.mongodb.database=${MONGO_DB_NAME:sirha}

### Variables de entorno (usadas en GitHub Actions / Azure)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:sirha}
server.port=${PORT:8080}

admin.email=juan.ccastellanos@mailescuelaing.edu.co
admin.password=${ADMIN_PASSWORD:admin123}