spring.application.name=PAWPATROL_BACK_PREPROD

spring.data.mongodb.database=sirha_preprod

admin.email=juan.ccastellanosad@mail.escuelaing.edu.co
admin.password=${ADMIN_PASSWORD}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
