spring.application.name=PAWPATROL_BACK_QA
spring.profiles.active=qa
server.port=${PORT:8080}

spring.data.mongodb.uri=${DATABASE_URL:}
spring.data.mongodb.database=sirha-qa-bd

admin.email=juan.ccastellanos@mailescuelaing.edu.co
admin.password=${ADMIN_PASSWORD}
