package eci.edu.dosw.proyecto.enums;

/**
 * Enumeración para manejar la facultad.
 */
public enum Faculty {
    INGENIERIA_DE_SISTEMAS,
    INGENIERIA_CIVIL,
    INGENIERIA_BIOMEDICA,
    INGENIERIA_MECANICA,
    MATEMATICAS,
    ADMINISTRACION_DE_EMPRESAS,
    ECONOMIA,
    INGENIERIA_ELECTRONICA,
    INGENIERIA_INDUSTRIAL,
    INGENIERIA_ELECTRICA,
    INGENIERIA_ESTADISTICA,
    INGENIERIA_AMBIENTAL,
    INGENIERIA_DE_CIBERSEGURIDAD,
    INGENIERIA_DE_INTELIGENCIA_ARTIFICIAL,
    INGENIERIA_DE_BIOTECNOLOGIA
}

