name: Build, test to Preprod (CI)

on:
  push:
    branches:
      - preprod
  workflow_dispatch:

env:
  SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
  SPRING_DATA_MONGODB_URI: ${{ secrets.SPRING_DATA_MONGODB_URI }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  ADMIN_EMAIL: juan.ccastellanos@mailescuelaing.edu.co

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment: preprod

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build and test
        run: mvn clean verify -DskipTests=false

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: ${{ github.workspace }}/target/site/jacoco/

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: pawpatrol-app
          path: target/*.jar
